name: Security Audit

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: '0 6 * * 1'

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - uses: rustsec/audit-check@cf4e2c7c2a7d47e48ae9a9723d3d72a09d4f8905  # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
