name: Security Audit

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: '0 6 * * 1'

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v4.2.2

      - uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998  # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
